import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/rootVariables.css";
import "./globals.css";
import CustomLayout from "@/components/CustomLayout";
import SiteHeader from "@/components/shared/Header/SiteHeader";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className="antialiased"
        suppressHydrationWarning
      >
        <CustomLayout>
          {/*<SiteHeader>*/}
          {children}
          {/*</SiteHeader>*/}
        </CustomLayout>
      </body>
    </html>
  );
}
